apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todo-app
  name: todo-app
spec:
  replicas: {{ .Values.app.Deployment.replicas | default 2 }}
  selector:
    matchLabels:
      app: todo-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo-app
    spec:
      containers:
      - image: "{{ .Values.app.Deployment.image }}:{{ .Values.app.Deployment.tag }}"
        name: to-do-list-dltxt
        resources:
          requests:
            cpu: 500m
          limits:
            cpu: 1000m
        env:
         - name: DB_HOST
           valueFrom:
             configMapKeyRef:
               name: {{ .Values.mysql.ConfigMap_name }}
               key: DB_HOST
         - name: MYSQL_DATABASE
           valueFrom:
             configMapKeyRef:
               name: {{ .Values.mysql.ConfigMap_name }}
               key: MYSQL_DATABASE
         - name: MYSQL_USER
           valueFrom:
             configMapKeyRef:
               name: {{ .Values.mysql.ConfigMap_name }}
               key: MYSQL_USER
         - name: MYSQL_PASSWORD
           valueFrom:
             secretKeyRef:
               name: {{ .Values.mysql.Secret_name }}
               key: MYSQL_PASSWORD
status: {}