apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ToDo_app_stage
  name: ToDo_app_stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ToDo_app_stage
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ToDo_app_stage
    spec:
      containers:
      - image: toph2490/my_to_do_list
        name: myapp
        resources: {}
        env:
         - name: DB_HOST
           valueFrom:
             configMapKeyRef:
               name: ToDo_app_stage
               key: DB_HOST
         - name: DB_NAME
           valueFrom:
             configMapKeyRef:
               name: ToDo_app_stage
               key: MYSQL_DATABASE
         - name: DB_USER
           valueFrom:
             configMapKeyRef:
               name: ToDo_app_stage
               key: MYSQL_USER
         - name: DB_PASSWORD
           valueFrom:
             secretKeyRef:
               name: ToDo_app_stage
               key: MYSQL_PASSWORD
status: {}
